version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://rocketchat:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0

  hubot-natural:
    image: diegodorgam/hubot-natural:latest
    restart: unless-stopped
    environment:
      - HUBOT_ADAPTER=rocketchat
      - HUBOT_OWNER=RocketChat
      - HUBOT_NAME='CatBot'
      - HUBOT_DESCRIPTION="Natural Language Processing with hubot"
      - HUBOT_HTTPD=false
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_USESSL=false
      - RESPOND_TO_DM=true
      - RESPOND_TO_LIVECHAT=true
      - LISTEN_ON_ALL_PUBLIC=false
      - ROCKETCHAT_USER=catbot
      - ROCKETCHAT_PASSWORD=123456
      - ROCKETCHAT_AUTH=password
      - HUBOT_LOG_LEVEL=debug
      - NATURAL_CORPUS=training_data/catbot-en.yml
      - NATURAL_LANG='en'
      # - LIVECHAT_DEPARTMENT_ID=kotKaj9JptWvwtJfJ
    volumes:
      - ./scripts:/hubotnatural/scripts
      - ./training_data:/hubotnatural/training_data
    depends_on:
      - rocketchat
    ports:
      - 8080:8080
